apiVersion: v1
kind: Service
metadata:
  name: java-api-service
spec:
  type: NodePort
  selector:
    app: java-api
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080 # You can choose a port in the 30000–32767 range

